[package]
	edition = "2021"
	name = "big_uf"
	version = "0.1.0"

[dependencies]
	crossbeam-channel = "0.5"
	ouroboros = "0.15"
	rayon = "1"
	rocksdb = "0.19"

[profile.test]
	opt-level = 2

[profile.dev]
	opt-level = 2

[profile.release]
	debug = 2
